// TODO: should probs just include in eslint-config...
// TODO: or can we finally give up and convert configs to ts...
declare module "@pentible/eslint-config/naming" {
    export const naming: unknown[];
}
