name: publish
on:
  release:
    types:
      - published
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.set_workspaces.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v4
      - id: set_workspaces
        run: |
          echo "workspaces=$(
            npm query '.workspace' --package-lock-only --expect-results \
            | jq --compact-output '[
              .[] | . += { name_unscoped: (.name | sub("^@.*/"; "")) }
            ]'
          )" >> $GITHUB_OUTPUT
  publish:
    name: Publish ${{ matrix.workspace.name_unscoped }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.matrix.outputs.workspaces) }}
    defaults:
      run:
        working-directory: ${{ matrix.workspace.location }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
        working-directory: ./
      - name: Build
        run: npm run build --if-present
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
