name: publish
on:
  release:
    types:
      - published
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set_packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v2
      - id: set_packages
        run: |
          echo "::set-output name=packages::$(
            find packages -mindepth 1 -maxdepth 1 -exec basename '{}' ';' \
            | jq --compact-output --raw-input -n '[inputs]'
          )"
  publish:
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.matrix.outputs.packages) }}
    defaults:
      run:
        working-directory: ./packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
        working-directory: ./
      - name: Build
        run: npm run build --if-present
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
