name: validate
on: push
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
