name: validate
on: push
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm install
      # lint
      - run: npx check-package-lock
      - run: npx shellcheck-all
      - run: yamllint --strict .
      - run: npx tsc -b
      - run: ESLINT_USE_FLAT_CONFIG=false npx eslint .
      - run: npx prettier --log-level warn --check .
